include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: fasle
    implicit-dynamic: false


linter:
  rules:
   # - prefer_const_constructors
    #- prefer_const_declarations

